services:
  - type: web
    name: vuln-scanner-api
    runtime: node
    rootDir: .
    buildCommand: pnpm install && cd apps/api && npx prisma generate
    startCommand: cd apps/api && npx prisma migrate deploy && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: redis://default:********@steady-baboon-66720.upstash.io:6379
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: worker
    name: vuln-scanner-worker
    runtime: node
    rootDir: .
    buildCommand: pnpm install && cd apps/api && npx prisma generate
    startCommand: cd apps/api && pnpm start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: redis://default:********@steady-baboon-66720.upstash.io:6379
        sync: false